'use strict';
// All coordinates, availability, distances and speech are demo data, not campus facts.
const nodes = {
  nw:[180,155],n:[400,155],ne:[620,155],w:[180,350],c:[400,350],e:[620,350],
  sw:[180,555],s:[400,555],se:[620,555],a:[530,260],ad:[530,350],
  b:[245,465],bd:[245,555],d:[620,460],gate:[400,655]
};
const edges = [['nw','n'],['n','ne'],['nw','w'],['w','sw'],['n','c'],['c','s'],['ne','e'],['e','d'],['d','se'],['w','c'],['c','ad'],['ad','e'],['sw','bd'],['bd','s'],['s','se'],['s','gate'],['ad','a'],['bd','b']];
const starts = [
  {id:'c',name:'Sân trung tâm',hint:'Ở giữa campus, cạnh lối đi bộ',icon:'location'},
  {id:'gate',name:'Cổng vào campus',hint:'Khu vực đón khách phía nam',icon:'gate'},
  {id:'sw',name:'Lối vào thư viện',hint:'Phía tây, trước khu thư viện',icon:'book'},
  {id:'ne',name:'Khu học tập phía đông',hint:'Gần lối vào tòa học tập',icon:'building'}
];
const waters = [
  {id:'A',node:'a',name:'Sảnh học tập',place:'Tầng 1 · Lối vào phía sân trung tâm',type:'refill',label:'Uống nước & refill',hint:'Máy nước cạnh cửa kính, phía bên phải sảnh.',hours:'07:00 – 21:00',color:'#d7dfc4'},
  {id:'B',node:'b',name:'Góc nước thư viện',place:'Tầng 1 · Sảnh ngoài thư viện',type:'refill',label:'Uống nước & refill',hint:'Máy nước ở cuối sảnh, cạnh băng ghế dài.',hours:'08:00 – 20:00',color:'#e6d7bc'},
  {id:'C',node:'d',name:'Khu sinh hoạt',place:'Tầng 1 · Hành lang hướng ra sân',type:'drink',label:'Vòi uống trực tiếp',hint:'Vòi nước gắn tường ngay cạnh lối vào khu sinh hoạt.',hours:'07:00 – 22:00',color:'#cddedc'}
];
const icons = {
 location:'<circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/><path d="M12 2v4m0 12v4M2 12h4m12 0h4"/>',
 drop:'<path d="M12 3C9 8 5 11 5 15a7 7 0 0 0 14 0c0-4-4-7-7-12Z"/>',
 mic:'<rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>',
 arrow:'<path d="M5 19 19 5M5 5h14v14"/>', back:'<path d="m14 5-7 7 7 7"/>',
 book:'<path d="M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3ZM12 6v15"/>',
 building:'<path d="M5 22V3h14v19M2 22h20M9 7h1m4 0h1M9 11h1m4 0h1M9 15h1m4 0h1M10 22v-3h4v3"/>',
 gate:'<path d="M4 21V4h16v17M8 21V8h8v13M2 21h20"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 check:'<path d="m5 12 4 4L19 6"/>', walk:'<circle cx="14" cy="4" r="2"/><path d="m8 11 4-4 3 5 4 1M12 7l-2 8-4 6m4-6 5 2 2 4"/>',
 shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.location}</svg>`;
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={origin:'c',located:false,selected:'A',filter:'all',query:'',blocked:new Set(),step:0,zoom:1,rating:0,feedback:false,loading:false};
let timer,searchTimer,toastTimer,lastFocus;
const app=document.getElementById('app');
const pointDistance=(a,b)=>Math.hypot(nodes[a][0]-nodes[b][0],nodes[a][1]-nodes[b][1]);
function route(start,end){
  const costs=Object.fromEntries(Object.keys(nodes).map(k=>[k,Infinity]));
  const prev={},todo=new Set(Object.keys(nodes));costs[start]=0;
  while(todo.size){const u=[...todo].sort((a,b)=>costs[a]-costs[b])[0];todo.delete(u);if(u===end)break;
    for(const [a,b] of edges){const v=a===u?b:b===u?a:null;if(!v||!todo.has(v))continue;const alt=costs[u]+pointDistance(u,v);if(alt<costs[v]){costs[v]=alt;prev[v]=u;}}
  }
  const path=[end];while(path[0]!==start){if(!prev[path[0]])return {path:[],meters:0,minutes:0};path.unshift(prev[path[0]]);}
  const meters=Math.round(costs[end]*.55/5)*5;return {path,meters,minutes:Math.max(1,Math.ceil(meters/70))};
}
function choices(){return waters.filter(w=>!state.blocked.has(w.id)&&(state.filter!=='refill'||w.type==='refill')).map(w=>({...w,...route(state.origin,w.node)})).sort((a,b)=>a.meters-b.meters);}
function selected(){return waters.find(w=>w.id===state.selected)||waters[0];}
function currentRoute(){return route(state.origin,selected().node);}
function originName(){return starts.find(s=>s.id===state.origin)?.name||'Mốc đã chọn trên bản đồ';}
function screen(){return (location.hash.slice(1)||'welcome').split('?')[0];}
function go(next){dismissDialog();if(location.hash==='#'+next)render();else location.hash=next;}
function toast(text){document.querySelector('.toast')?.remove();clearTimeout(toastTimer);const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=text;document.body.append(el);toastTimer=setTimeout(()=>el.remove(),4000);}
function stepper(active){return `<div class="steps" aria-label="Tiến trình">${['Vị trí','Tìm nước','Đường đi','Đã đến'].map((s,i)=>`${i?'<i></i>':''}<span class="${i===active?'current':''}"><b>${i<active?'✓':i+1}</b>${s}</span>`).join('')}</div>`;}
function header(){return `<header class="topbar"><a href="#welcome" class="brand" aria-label="Vmap trang chủ"><span class="brand-mark">↗</span>vmap<span style="color:#91a56e">.</span></a><nav class="topnav" aria-label="Điều hướng"><a href="#search" class="${screen()!=='welcome'?'active':''}">Khám phá</a><span class="desktop">Find water. Keep learning.</span><span class="demo-badge">DEMO TƯƠNG TÁC</span></nav></header>`;}
function footer(){return '<footer class="footer"><span>VMAP / 1PROMPT &nbsp; · &nbsp; AI20k Mini Hackathon</span><span>Vị trí, sơ đồ campus, điểm nước và trạng thái đều giả lập · Không thu âm / GPS</span></footer>';}
function heading(eyebrow,title,subtitle,step){return `<div class="heading-row"><div><div class="eyebrow">${eyebrow}</div><h1 tabindex="-1" id="page-title">${title}</h1><p>${subtitle}</p></div>${stepper(step)}</div>`;}
function positionCard(){return `<section class="card"><div class="position"><span class="loc-symbol">${icon('location')}</span><div><strong>${esc(originName())}</strong><small>Vị trí đã chọn · Demo</small></div><button class="text-button" data-action="location">Đổi</button></div></section>`;}
function map({locate=false,hero=false}={}){
  const sc=screen(),showRoute=hero||['results','detail','navigate','arrived'].includes(sc);
  const r=currentRoute(),walking=sc==='navigate',reached=sc==='arrived';
  const cursor=reached?selected().node:walking?r.path[Math.min(state.step,r.path.length-1)]:state.origin;
  const [px,py]=nodes[cursor];
  const routePath=showRoute&&!state.blocked.has(state.selected)?r.path.map(n=>nodes[n].join(',')).join(' '):'';
  const trees=[[150,195],[150,238],[150,284],[335,193],[335,239],[335,287],[450,191],[450,231],[660,228],[660,274],[151,403],[151,449],[333,410],[334,461],[448,406],[450,454],[662,403],[662,450],[210,593],[250,593],[565,599],[615,600],[738,300],[738,344],[737,389]];
  return `<section class="map-shell" aria-label="Bản đồ campus tương tác giả lập"><svg class="campus-map" id="campus-map" viewBox="${400-400/state.zoom} ${360-360/state.zoom} ${800/state.zoom} ${720/state.zoom}" preserveAspectRatio="xMidYMid meet" role="group" aria-label="Bản đồ demo. Chấm xanh là vị trí bạn. ${locate?'Chọn mốc vị trí bằng các nút trên bản đồ.':'Chọn điểm nước để xem chi tiết.'}">
    <defs><pattern id="grass" width="17" height="17" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r=".7" fill="#bdc9aa" opacity=".5"/></pattern><g id="tree"><circle r="14" fill="#c3d5ac"/><circle cx="-3" cy="-3" r="10" fill="#d0dfbd"/></g><filter id="pin-shadow" x="-60%" y="-60%" width="220%" height="220%"><feDropShadow dx="0" dy="4" stdDeviation="4" flood-color="#224331" flood-opacity=".17"/></filter></defs>
    <rect width="800" height="720" fill="#e9edde"/><rect width="800" height="720" fill="url(#grass)"/>
    <path d="M-20 85H820M-20 630H820M87-20V740M709-20V740" stroke="#d7ddce" stroke-width="40" fill="none"/><path d="M-20 85H820M-20 630H820M87-20V740M709-20V740" stroke="#f9f7ef" stroke-width="31" fill="none"/>
    ${edges.map(([a,b])=>`<line x1="${nodes[a][0]}" y1="${nodes[a][1]}" x2="${nodes[b][0]}" y2="${nodes[b][1]}" stroke="#faf8ef" stroke-width="19"/>`).join('')}
    <rect x="213" y="192" width="99" height="104" rx="7" fill="#c9cebd"/><rect x="213" y="184" width="99" height="104" rx="7" fill="#e0e2d3" stroke="#c8cebd"/><rect x="226" y="197" width="72" height="76" rx="2" fill="#ebeadd"/>
    <path d="M478 187H657V291H572V240H478Z" fill="#c1cbb3"/><path d="M478 180H657V283H572V233H478Z" fill="#dce3ca" stroke="#becba9"/><path d="M490 193H642V268H586V218H490Z" fill="#e9eddd"/>
    <rect x="211" y="409" width="102" height="82" rx="5" fill="#cfccbb"/><rect x="211" y="401" width="102" height="82" rx="5" fill="#e5e0cd" stroke="#d1cbb5"/><rect x="224" y="413" width="75" height="57" fill="#f0ebdd" rx="2"/>
    <rect x="476" y="410" width="105" height="91" rx="5" fill="#bfcfc4"/><rect x="476" y="403" width="105" height="91" rx="5" fill="#d9e3d7" stroke="#c1cebd"/><rect x="490" y="415" width="77" height="63" fill="#e8edde" rx="3"/>
    <rect x="19" y="204" width="33" height="291" rx="16" fill="#c5dad5"/><path d="M30 220q25 35 0 70t0 70t0 70" stroke="#deebe2" stroke-width="2" fill="none"/>
    <rect x="349" y="418" width="29" height="65" rx="14" fill="#d2ddbc"/><rect x="414" y="418" width="29" height="65" rx="14" fill="#d2ddbc"/>
    ${trees.map(([x,y])=>`<use href="#tree" x="${x}" y="${y}"/>`).join('')}
    <g fill="#8c967f" font-size="9" text-anchor="middle" letter-spacing=".4"><text x="263" y="237">KHU HỌC TẬP</text><text x="560" y="211">SẢNH HỌC TẬP</text><text x="263" y="442">THƯ VIỆN</text><text x="529" y="449">KHU SINH HOẠT</text><text x="398" y="512" font-size="8" letter-spacing="2">SÂN TRUNG TÂM</text><text x="400" y="695" font-size="9" letter-spacing="2">CỔNG CAMPUS</text><text x="400" y="111" font-size="8" letter-spacing="2">LỐI ĐI BỘ</text></g>
    ${routePath?`<polyline points="${routePath}" stroke="#fffdf5" stroke-width="12" stroke-linecap="round" stroke-linejoin="round" fill="none"/><polyline class="route-line" points="${routePath}" stroke="#62894b" stroke-width="5" stroke-linecap="round" stroke-linejoin="round" fill="none"/>`:''}
    ${waters.map(w=>{const [x,y]=nodes[w.node],blocked=state.blocked.has(w.id);return `<g class="map-pin" transform="translate(${x},${y})" role="button" tabindex="0" data-water="${w.id}" aria-label="Điểm nước ${w.id}, ${w.name}${blocked?', đã báo không hoạt động':''}"><title>${w.name} · ${w.label}${blocked?' · Không hoạt động':''}</title><circle cy="-12" r="26" fill="transparent"/><path class="pin-body" d="M0 8C-4 2-17-10-17-20a17 17 0 1 1 34 0C17-10 4 2 0 8Z" fill="${blocked?'#aaa899':w.id===state.selected&&showRoute?'#173f35':'#6e8557'}" filter="url(#pin-shadow)"/><text y="-16" text-anchor="middle" font-size="13" fill="#fffef0" font-weight="700">${blocked?'×':w.id}</text>${w.id===state.selected&&showRoute&&!blocked?`<rect x="25" y="-43" width="133" height="43" rx="9" fill="#fffef8"/><text x="35" y="-26" font-size="9" fill="#173f35" font-weight="700">${w.name}</text><text x="35" y="-11" font-size="8" fill="#7d876f">${r.meters} m · ${r.minutes} phút · mẫu</text>`:''}</g>`;}).join('')}
    ${locate?starts.map(s=>{const [x,y]=nodes[s.id];return `<g class="map-pin" role="button" tabindex="0" data-origin="${s.id}" aria-label="Chọn vị trí ${s.name}"><circle cx="${x}" cy="${y}" r="24" fill="#fff" fill-opacity=".8" stroke="#81986b" stroke-dasharray="3 4"/><circle cx="${x}" cy="${y}" r="6" fill="#77915c"/></g>`;}).join(''):''}
    <g pointer-events="none"><circle cx="${px}" cy="${py}" r="32" fill="#4285ed" opacity=".10"/><circle cx="${px}" cy="${py}" r="21" fill="#4285ed" opacity=".13"/><circle cx="${px}" cy="${py}" r="9" fill="#4285ed" stroke="white" stroke-width="4"/><rect x="${px-57}" y="${py+25}" width="114" height="29" rx="14" fill="#fffef8"/><text x="${px}" y="${py+44}" text-anchor="middle" fill="#3766a1" font-size="9" font-weight="600">${reached?'Bạn đã đến nơi':walking?'Bạn đang di chuyển':'Bạn đang ở đây'}</text></g>
    </svg><div class="map-overlay-top"><div class="map-label">⌖ &nbsp; VinUni Campus<small>Sơ đồ minh họa, không phải bản đồ thực địa</small></div><div class="map-tag">${state.blocked.size?3-state.blocked.size:3} điểm nước khả dụng · mẫu</div></div><div class="compass" aria-hidden="true">N<span>↑</span></div>${locate?'<div class="map-tip">Chạm một mốc trên bản đồ để đặt vị trí</div>':''}<div class="map-bottom"><div class="legend"><span><i></i>Bạn</span><span><i class="green"></i>Điểm nước</span><span><i class="line"></i>Đường đi</span></div>${hero?'':`<div class="map-controls"><button data-action="zoom-out" aria-label="Thu nhỏ bản đồ">−</button><button data-action="zoom-in" aria-label="Phóng to bản đồ">+</button><button data-action="recenter" aria-label="Đặt lại khung nhìn bản đồ">⌖</button></div>`}</div></section>`;
}
function welcome(){return `<main class="page"><div class="hero"><div class="hero-copy"><div class="eyebrow">NGƯỜI BẠN NHỎ TRÊN CAMPUS</div><h1>Khát rồi?<br>Để Vmap<br><em>dẫn bạn đi.</em></h1><p>Tìm điểm lấy nước quanh bạn bằng một câu nói. Có đường đi rõ ràng, để bạn nhanh chóng quay lại điều đang làm.</p><button class="button" data-action="start">Tìm nước gần tôi ${icon('arrow')}</button><span class="tiny muted">Trải nghiệm thử · Không cần tài khoản</span><div class="hero-features"><div><b>01 câu nói</b><span class="muted">Để bắt đầu tìm nước</span></div><div><b>Từng bước</b><span class="muted">Dễ dàng theo đường đi</span></div><div><b>Ngay gần bạn</b><span class="muted">Gợi ý theo vị trí</span></div></div></div><div class="hero-map">${map({hero:true})}<div class="hero-float"><span class="loc-symbol">${icon('drop')}</span><div><strong>Một điểm nước, ngay gần đây.</strong><small>Chọn vị trí để khám phá hành trình của bạn.</small></div></div></div></div>${footer()}</main>`;}
function locationPage(){return `<main class="page screen-location">${heading('BƯỚC 01 / VỊ TRÍ','Bạn đang ở đâu?','Chọn một điểm bắt đầu để Vmap tìm đường cho bạn.',0)}<div class="workspace"><aside class="sidebar"><section class="card"><div class="kicker">CHỌN VỊ TRÍ DEMO</div><p class="small muted">Chạm một mốc trên bản đồ hoặc chọn bên dưới.</p><div class="stack">${starts.map(s=>`<button class="place-option ${s.id===state.origin?'selected':''}" data-origin="${s.id}" aria-pressed="${s.id===state.origin}">${icon(s.icon)}<span><strong>${s.name}</strong><small>${s.hint}</small></span><i class="radio"></i></button>`).join('')}</div><button class="button full mt" data-action="confirm-location">Tìm nước từ đây ${icon('arrow')}</button><button class="text-button mt" data-action="unknown">Tôi không rõ mình đang ở đâu</button></section><div class="notice">Đây là vị trí giả lập. Ứng dụng không xin quyền định vị và không sử dụng GPS của điện thoại.</div></aside>${map({locate:true})}</div>${footer()}</main>`;}
function searchPage(){return `<main class="page screen-search">${heading('BƯỚC 02 / NHU CẦU','Bạn muốn tìm gì?','Nói một câu, chọn một gợi ý, hoặc nhập điều bạn cần.',1)}<div class="workspace"><aside class="sidebar">${positionCard()}<section class="card search-card"><div class="kicker">CỨ NÓI, VMAP SẼ HIỂU</div><h2>“Chỉ tôi chỗ lấy nước<br>gần nhất nhé.”</h2><p>Mình sẽ tìm điểm nước phù hợp, tính từ vị trí bạn vừa chọn.</p><div class="row mt"><button class="mic" data-action="voice" aria-label="Thử giọng nói giả lập">${icon('mic')}</button><div class="mic-caption">Chạm để thử giọng nói<small>Câu nói mẫu · Không thu âm</small></div></div><form class="query-form" id="query-form"><input name="query" aria-label="Yêu cầu tìm nước" placeholder="Hoặc gõ yêu cầu của bạn…" maxlength="200" autocomplete="off" value="${esc(state.query)}"><button type="submit" aria-label="Gửi yêu cầu">${icon('arrow')}</button></form><div class="chips mt"><button class="quick-query" data-query="Tìm nước uống gần nhất">Nước uống gần nhất</button><button class="quick-query" data-query="Tôi muốn refill bình nước">Refill bình nước</button></div></section><section class="card"><div class="row">${icon('shield')}<h3 style="margin:0">Một lựa chọn rõ ràng</h3></div><p class="small muted">Gợi ý gồm khoảng cách đi bộ, loại điểm nước và mốc nhận biết khi đến nơi.</p><span class="tiny muted">Trong demo, yêu cầu được xử lý bằng kịch bản có sẵn.</span></section></aside>${map()}</div>${footer()}</main>`;}
function waterCard(w,index){return `<article class="water-card ${w.id===state.selected?'selected':''}"><button class="card-open" data-water="${w.id}" aria-label="Xem điểm nước ${w.id}, ${w.name}, ${w.meters} mét"><div class="row spread"><span class="number">${w.id}</span><span class="pill">${index===0?'Gần nhất':'Phương án khác'}</span></div><h3>${w.name}</h3><p>${w.place}</p><div class="row spread"><span class="distance">${w.meters}<small> m · ${w.minutes} phút</small></span><span class="tiny muted">${w.type==='refill'?'Có refill':'Uống trực tiếp'} &nbsp; ↗</span></div></button></article>`;}
function resultsPage(){const items=choices();return `<main class="page screen-results">${heading('BƯỚC 02 / GỢI Ý',state.loading?'Đang tìm điểm nước…':items.length?'Một ngụm nước, ngay gần bạn.':'Chưa có điểm nước phù hợp',state.loading?'Đang đối chiếu các điểm nước với vị trí của bạn.':`Từ ${esc(originName())} · Khoảng cách theo lối đi trong sơ đồ demo.`,1)}<div class="workspace"><aside class="sidebar">${positionCard()}${state.loading?'<section class="card loading" role="status"><div><div class="spinner"></div><h3>Đang tìm đường gần nhất</h3><p class="small muted">Đối chiếu loại điểm nước và lối đi…</p></div></section>':`<section class="card"><div class="kicker">YÊU CẦU CỦA BẠN</div><p class="small">“${esc(state.query||'Tìm nước uống gần nhất')}”</p><div class="chips"><button class="chip ${state.filter==='all'?'active':''}" data-filter="all" aria-pressed="${state.filter==='all'}">Tất cả điểm nước</button><button class="chip ${state.filter==='refill'?'active':''}" data-filter="refill" aria-pressed="${state.filter==='refill'}">Có refill bình</button></div></section><div class="row spread"><span class="kicker">${items.length} ĐIỂM PHÙ HỢP</span><button class="text-button" data-action="search">Đổi yêu cầu</button></div><div class="result-list">${items.map(waterCard).join('')||'<section class="card"><h3>Thử một lựa chọn khác nhé</h3><p class="small muted">Các điểm phù hợp đã được báo không hoạt động trong lượt demo này. Bạn có thể đổi bộ lọc hoặc bắt đầu lượt mới.</p><button class="button full secondary" data-action="restart">Bắt đầu lượt demo mới</button></section>'}</div><p class="tiny muted">Trạng thái “khả dụng” là dữ liệu mẫu, chưa xác minh thực địa.</p>`}</aside>${map()}</div>${footer()}</main>`;}
function art(w){return `<div class="detail-art"><svg viewBox="0 0 400 170" role="img" aria-label="Hình minh họa điểm nước, không phải ảnh thực tế"><rect width="400" height="170" fill="${w.color}"/><path d="M0 135h400v35H0Z" fill="#bec9b2"/><rect x="27" y="23" width="83" height="107" rx="3" fill="#edf1e3"/><path d="M68 23v107M27 77h83" stroke="#c8d3be" stroke-width="4"/><rect x="269" y="43" width="101" height="63" fill="#f4f2e8"/><text x="319" y="68" text-anchor="middle" font-family="system-ui" font-size="10" fill="#708462">REFILL &amp; GO</text><path d="M296 83h46" stroke="#adc391" stroke-width="3"/><rect x="163" y="30" width="68" height="113" rx="8" fill="#f9faf5"/><rect x="172" y="45" width="50" height="58" rx="4" fill="#355e50"/><path d="M185 63v13m22-13v13" stroke="#d4e7b6" stroke-width="4"/><rect x="178" y="93" width="38" height="5" rx="2" fill="#8ba893"/><rect x="188" y="113" width="20" height="21" rx="3" fill="#dce4d4"/><rect x="125" y="116" width="19" height="25" rx="3" fill="#d5bb95"/><path d="M135 117q-33-31-10-43 14 0 10 43m0 0q31-34 12-42-16 6-12 42" fill="#709061"/><text x="383" y="157" text-anchor="end" font-family="system-ui" font-size="8" fill="#6e7b61">HÌNH MINH HỌA</text></svg></div>`;}
function detailPage(){const w=selected(),r=currentRoute();return `<main class="page screen-detail">${heading('ĐIỂM NƯỚC / '+w.id,'Một điểm dừng thật nhẹ.','Xem thông tin và chọn bắt đầu khi bạn sẵn sàng.',1)}<div class="workspace"><aside class="sidebar"><section class="card"><button class="back" data-action="results">${icon('back')} Tất cả gợi ý</button>${art(w)}<div class="row spread"><span class="pill">Khả dụng · giả lập</span><span class="tiny muted">Điểm ${w.id}</span></div><h2 class="mt">${w.name}</h2><p class="small muted">${w.place}</p><div class="detail-stats"><div><strong>${r.meters}<span> m</span></strong><small>Quãng đường mô phỏng</small></div><div><strong>${r.minutes}<span> phút</span></strong><small>Đi bộ theo lối trong sơ đồ</small></div></div><div class="info-line">${icon('drop')}${w.label}</div><div class="info-line">${icon('clock')}${w.hours} · Giờ mở cửa mẫu</div><div class="info-line">${icon('location')}${w.hint}</div><button class="button full mt" data-action="navigate">Bắt đầu chỉ đường ${icon('arrow')}</button><button class="text-button mt" data-action="report">Báo điểm nước không dùng được</button></section></aside>${map()}</div>${footer()}</main>`;}
function direction(a,b){const [x,y]=nodes[a],[u,v]=nodes[b];return Math.abs(u-x)>Math.abs(v-y)?u>x?'đông':'tây':v>y?'nam':'bắc';}
function segmentInstruction(path,i){const a=path[i],b=path[i+1];if(!b)return 'Điểm nước ở ngay trước bạn';const next=direction(a,b),prior=i?direction(path[i-1],a):null;const turn=!prior?'Đi theo lối đi':prior===next?'Tiếp tục đi thẳng':'Đổi hướng tại giao lối';return `${turn} về phía ${next}`;}
function navigatePage(){const w=selected(),r=currentRoute(),total=Math.max(1,r.path.length-1);state.step=Math.min(state.step,total-1);const remaining=route(r.path[state.step],w.node);return `<main class="page screen-navigate">${heading('BƯỚC 03 / DẪN ĐƯỜNG','Cùng đi lấy nước nhé.','Nhấn “Đi tiếp” để mô phỏng di chuyển trên bản đồ.',2)}<div class="workspace"><aside class="sidebar"><div class="instruction"><span class="arrow">${state.step?'↱':'↑'}</span><div><strong>${segmentInstruction(r.path,state.step)}</strong><small>Khoảng ${Math.round(pointDistance(r.path[state.step],r.path[state.step+1])*.55/5)*5} m đến mốc tiếp theo · mô phỏng</small></div></div><section class="card"><div class="row spread"><div><div class="kicker">ĐANG ĐẾN ĐIỂM ${w.id}</div><h3 class="mt">${w.name}</h3></div>${icon('drop')}</div><div class="detail-stats"><div><strong>${remaining.meters}<span> m</span></strong><small>Còn lại · mẫu</small></div><div><strong>${remaining.minutes}<span> phút</span></strong><small>Thời gian ước tính</small></div></div><div class="row spread tiny muted"><span>Hành trình của bạn</span><span>${state.step} / ${total} chặng</span></div><div class="progress-bar" role="progressbar" aria-label="Tiến độ hành trình" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${state.step}"><div style="width:${state.step/total*100}%"></div></div>${r.path.slice(0,-1).map((n,i)=>`<div class="walk-step ${i===state.step?'active':i<state.step?'done':''}"><b>${i<state.step?'✓':i+1}</b><span>${segmentInstruction(r.path,i)}${i===total-1?'<br>Đến '+w.name:''}</span></div>`).join('')}<button class="button full mt" data-action="walk">${state.step===total-1?'Đến điểm nước':'Đi tiếp một chặng'} ${icon('arrow')}</button><div class="row spread mt"><button class="text-button" data-action="exit-route">Dừng chỉ đường</button><button class="text-button" data-action="report">Báo sự cố</button></div></section><div class="notice">Vị trí di chuyển bằng kịch bản demo, không theo dõi chuyển động thực của bạn.</div></aside>${map()}</div>${footer()}</main>`;}
function arrivedPage(){const w=selected();return `<main class="page screen-arrived">${heading('BƯỚC 04 / ĐÃ ĐẾN','Đến nơi rồi. Nạp lại năng lượng!','Một ngụm nước, rồi trở lại điều bạn đang làm.',3)}<div class="workspace"><aside class="sidebar"><section class="card"><div class="success"><div class="success-icon">✓</div><h2>Bạn đã đến điểm ${w.id}</h2><p>${w.name}<br>${w.place}</p></div>${art(w)}<p class="small">${w.hint}</p>${state.feedback?'<div class="notice" role="status">Đã ghi nhận phản hồi trong lượt demo này. Cảm ơn bạn đã giúp trải nghiệm rõ ràng hơn!</div>':`<button class="button full" data-action="found">${icon('check')} Tôi đã lấy được nước</button><button class="button full outline mt" data-action="report">Điểm nước không dùng được</button>`}<div class="mt" style="text-align:center"><span class="tiny muted">Đường đi có dễ theo dõi không?</span><div class="rating" role="group" aria-label="Đánh giá trải nghiệm">${[1,2,3,4,5].map(n=>`<button class="${n<=state.rating?'chosen':''}" data-rating="${n}" aria-label="${n} sao" aria-pressed="${state.rating===n}">★</button>`).join('')}</div></div><button class="button full secondary" data-action="restart">Thử một hành trình khác</button></section></aside>${map()}</div>${footer()}</main>`;}
function render(){
  const sc=screen();
  if(!['welcome','location','search','results','detail','navigate','arrived'].includes(sc)){location.hash='welcome';return;}
  if(!state.located&&['search','results','detail','navigate','arrived'].includes(sc)){location.hash='location';return;}
  if(['detail','navigate','arrived'].includes(sc)&&state.blocked.has(state.selected)){location.hash='results';return;}
  app.innerHTML=header()+({welcome,location:locationPage,search:searchPage,results:resultsPage,detail:detailPage,navigate:navigatePage,arrived:arrivedPage}[sc])();
  document.title=`Vmap · ${{welcome:'Tìm nước, tiếp hành trình',location:'Bạn đang ở đâu?',search:'Tìm nước',results:'Điểm nước gần bạn',detail:selected().name,navigate:'Đang dẫn đường',arrived:'Đã đến nơi'}[sc]}`;
}
function dismissDialog(){clearTimeout(timer);document.querySelector('.dialog-shade')?.remove();lastFocus?.focus();}
function dialog(content){lastFocus=document.activeElement;document.querySelector('.dialog-shade')?.remove();const shade=document.createElement('div');shade.className='dialog-shade';shade.innerHTML=`<section class="dialog" role="dialog" aria-modal="true" aria-label="Hộp thoại demo"><button class="close" data-action="close-dialog" aria-label="Đóng">×</button>${content}</section>`;document.body.append(shade);shade.querySelector('button')?.focus();}
function runQuery(query){const clean=query.trim();if(!clean){toast('Bạn hãy nhập yêu cầu hoặc chọn một câu gợi ý.');return;}
  state.query=clean;const normalized=clean.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  if(!/nuoc|refill|khat|uong/.test(normalized)){dialog(`<div class="voice-orb">${icon('drop')}</div><h2>Mình có thể giúp tìm nước</h2><p>Demo hỗ trợ tìm nước uống hoặc chỗ refill bình. Bạn muốn thử nhu cầu nào?</p><div class="dialog-actions"><button class="button" data-query="Tìm nước uống gần nhất">Tìm nước uống</button><button class="button secondary" data-query="Tôi muốn refill bình nước">Refill bình nước</button></div>`);return;}
  dismissDialog();state.filter=/refill|binh/.test(normalized)?'refill':'all';state.selected=choices()[0]?.id||'A';state.loading=true;go('results');
  clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.loading=false;if(screen()==='results')render();},650);
}
function showVoice(){dialog(`<div class="eyebrow" style="margin-top:15px">GIỌNG NÓI · GIẢ LẬP</div><div class="voice-orb">${icon('mic')}</div><h2>Đang nghe câu nói mẫu…</h2><div class="wave" aria-hidden="true">${'<i></i>'.repeat(13)}</div><p>Không thu âm. Bạn đang xem một kịch bản hội thoại có sẵn.</p>`);timer=setTimeout(()=>{if(!document.querySelector('.dialog'))return;dialog(`<div class="eyebrow" style="margin-top:15px">ĐÃ NHẬN CÂU NÓI MẪU</div><div class="voice-orb">${icon('check')}</div><h2>“Chỉ tôi chỗ lấy nước<br>gần nhất nhé.”</h2><p>Tìm từ ${esc(originName())}. Bạn có thể dùng câu này hoặc thử nhu cầu refill.</p><div class="dialog-actions"><button class="button" data-query="Chỉ tôi chỗ lấy nước gần nhất nhé">Tìm điểm nước ${icon('arrow')}</button><button class="button secondary" data-query="Tôi muốn refill bình nước">Tôi muốn refill bình</button></div>`);},1400);}
function showUnknown(){dialog(`<div class="voice-orb">${icon('location')}</div><h2>Nhìn quanh một chút nhé</h2><p>Bạn thấy mốc nào ở gần mình nhất? Chọn một mốc để đặt vị trí demo.</p><label class="field-label" for="landmark">Mốc gần bạn</label><select id="landmark" class="location-select">${starts.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select><button class="button full mt" data-action="resolve-location">Dùng mốc này</button><p class="tiny">Kịch bản hỏi lại khi chưa xác định được vị trí.</p>`);}
function showReport(){dialog(`<div class="voice-orb">${icon('drop')}</div><h2>Điểm ${selected().id} có vấn đề gì?</h2><p>Phản hồi chỉ lưu trong lượt demo. Mình sẽ tìm một điểm khác cho bạn.</p><form id="report-form" class="stack"><label class="report-label"><input type="radio" name="reason" value="Máy hết nước" checked>Máy hết nước</label><label class="report-label"><input type="radio" name="reason" value="Điểm nước đóng cửa">Điểm nước đóng cửa</label><label class="report-label"><input type="radio" name="reason" value="Không tìm thấy điểm nước">Không tìm thấy điểm nước</label><button class="button full mt" type="submit">Ghi nhận & tìm điểm khác ${icon('arrow')}</button></form>`);}
function report(){const w=selected();if(screen()==='navigate'){state.origin=currentRoute().path[state.step];}else if(screen()==='arrived'){state.origin=w.node;}state.blocked.add(w.id);state.selected=choices()[0]?.id||w.id;state.step=0;state.loading=false;dismissDialog();go('results');toast(`Đã loại điểm ${w.id} khỏi gợi ý trong lượt demo này.`);}
function reset(){clearTimeout(timer);clearTimeout(searchTimer);Object.assign(state,{origin:'c',located:false,selected:'A',filter:'all',query:'',blocked:new Set(),step:0,zoom:1,rating:0,feedback:false,loading:false});go('location');}
document.addEventListener('click',event=>{
  const el=event.target.closest('[data-action],[data-origin],[data-water],[data-filter],[data-query],[data-rating]');if(!el)return;
  if(el.dataset.origin){state.origin=el.dataset.origin;state.selected=choices()[0]?.id||'A';render();return;}
  if(el.dataset.water){if(screen()==='welcome'){go('location');return;}if(screen()==='location'){toast('Chọn mốc vị trí của bạn trước; các ghim A, B, C là điểm nước.');return;}if(state.blocked.has(el.dataset.water)){toast('Điểm này đã được báo không hoạt động trong lượt demo.');return;}if(screen()==='navigate'){toast('Hãy dừng chỉ đường trước khi chọn điểm nước khác.');return;}state.selected=el.dataset.water;go('detail');return;}
  if(el.dataset.filter){state.filter=el.dataset.filter;state.selected=choices()[0]?.id||state.selected;render();return;}
  if(el.dataset.query){runQuery(el.dataset.query);return;}
  if(el.dataset.rating){state.rating=Number(el.dataset.rating);render();toast(`Đã chọn ${state.rating} sao trong bản demo.`);return;}
  const action=el.dataset.action;
  if(['location','search','results'].includes(action)){state.loading=false;go(action);}
  else if(action==='start')go('location');
  else if(action==='confirm-location'){state.located=true;state.selected=choices()[0]?.id||'A';go('search');}
  else if(action==='unknown')showUnknown();
  else if(action==='resolve-location'){state.origin=document.getElementById('landmark').value;state.located=true;dismissDialog();go('search');}
  else if(action==='voice')showVoice();
  else if(action==='close-dialog')dismissDialog();
  else if(action==='navigate'){state.step=0;state.rating=0;state.feedback=false;go(currentRoute().path.length<2?'arrived':'navigate');}
  else if(action==='walk'){state.step++;if(state.step>=currentRoute().path.length-1)go('arrived');else render();}
  else if(action==='exit-route')go('detail');
  else if(action==='report')showReport();
  else if(action==='found'){state.feedback=true;render();}
  else if(action==='restart')reset();
  else if(action==='zoom-in'||action==='zoom-out'){state.zoom=Math.max(1,Math.min(1.7,state.zoom+(action==='zoom-in'?.2:-.2)));render();}
  else if(action==='recenter'){state.zoom=1;render();toast('Đã hiển thị toàn bộ hành trình trên bản đồ.');}
});
document.addEventListener('submit',event=>{if(event.target.id==='query-form'){event.preventDefault();runQuery(new FormData(event.target).get('query')||'');}if(event.target.id==='report-form'){event.preventDefault();report();}});
document.addEventListener('keydown',event=>{
  const modal=document.querySelector('.dialog');
  if(event.key==='Escape'&&modal){dismissDialog();return;}
  if(event.key==='Tab'&&modal){const focusable=[...modal.querySelectorAll('button,input,select')];const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
  if((event.key==='Enter'||event.key===' ')&&event.target.matches('g[role="button"]')){event.preventDefault();event.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}
});
window.addEventListener('hashchange',()=>{dismissDialog();if(screen()!=='results'){clearTimeout(searchTimer);state.loading=false;}render();window.scrollTo(0,0);document.getElementById('page-title')?.focus({preventScroll:true});});
render();
