const assert=require('node:assert/strict');
const N=require('./navigation.js');
const origin={kind:'node',nodeId:'west_gate'};
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
test('shared graph provenance and geometry',()=>{for(const e of N.data.edges){assert.equal(e.source,'simulated');assert.equal(e.distanceMeters,null);assert.deepEqual(e.geometry[0],[N.nodes[e.from].x,N.nodes[e.from].y]);assert.deepEqual(e.geometry.at(-1),[N.nodes[e.to].x,N.nodes[e.to].y]);}});
test('D route does not add water',()=>{const r=N.planTrip({origin,destinationId:'D'});assert.equal(r.status,'ok');assert.equal(r.destinationId,'d_entrance');assert.equal(r.waypointIds.length,0);});
test('strict indoor constraint never silently relaxed',()=>assert.equal(N.planTrip({origin,destinationId:'D',preference:'indoor_only'}).status,'no_route_under_constraints'));
test('covered alternative exists and has no exposed edges',()=>{const r=N.planTrip({origin,destinationId:'D',preference:'sheltered_only'});assert.equal(r.status,'ok');assert.equal(r.exposureSummary.exposed,0);assert.equal(r.exposureSummary.unknown,0);});
test('shelter ranking uses exposure first',()=>{const a=N.planTrip({origin,destinationId:'D'}),b=N.planTrip({origin,destinationId:'D',preference:'prefer_sheltered'});assert.ok(b.cost>a.cost);assert.ok(b.exposureSummary.exposed<a.exposureSummary.exposed);});
test('water exclusion and combined itinerary',()=>{const r=N.planTrip({origin,destinationId:'D',viaWater:true,excludedPointIds:['water_d']});assert.equal(r.status,'ok');assert.notEqual(r.waterPointId,'water_d');assert.equal(r.waypointIds.length,1);assert.equal(r.destinationId,'d_entrance');assert.equal(N.planTrip({origin,destinationId:'water',excludedPointIds:N.data.waterPoints.map(w=>w.id)}).status,'no_available');});
test('starts idle, moves partially and reroutes without snapping',()=>{const r=N.planTrip({origin,destinationId:'D'}),j=N.createJourney(r);assert.equal(j.motion,'idle');N.advance(j,20);const p=N.position(j);assert.equal(p.kind,'edge');const repl=N.planTrip({origin:p,destinationId:'water'}),k=N.createJourney(repl);assert.deepEqual(N.coordinates(N.position(k)),N.coordinates(p));});
test('frame rate independence and backward start clamp',()=>{const r=N.planTrip({origin,destinationId:'D'}),a=N.createJourney(r),b=N.createJourney(r);for(let i=0;i<10;i++)N.advance(a,3);N.advance(b,30);assert.ok(Math.abs(N.position(a).offset-N.position(b).offset)<1e-10);N.advance(a,-1000);assert.deepEqual(N.position(a),origin);});
test('door and stairs require confirmation in both directions',()=>{const r=N.planTrip({origin:{kind:'node',nodeId:'e_entrance'},destinationId:'water',excludedPointIds:N.data.waterPoints.filter(w=>w.id!=='water').map(w=>w.id)}),j=N.createJourney(r);N.advance(j,9999);assert.equal(j.pending.type,'transition');assert.equal(N.position(j).nodeId,'e_entrance');N.confirmStop(j);assert.equal(N.position(j).nodeId,'e_lobby_1');N.advance(j,9999);assert.equal(j.pending.type,'transition');assert.equal(j.pending.label,'Lên tầng');N.confirmStop(j);N.advance(j,9999);assert.equal(j.motion,'arrived');N.advance(j,-9999);assert.equal(j.pending.label,'Xuống tầng');N.confirmStop(j);N.advance(j,-9999);assert.equal(j.pending.label,'Ra tòa');N.confirmStop(j);assert.equal(N.position(j).nodeId,'e_entrance');});
test('large frame stops at intermediate water',()=>{const r=N.planTrip({origin,destinationId:'D',viaWater:true}),j=N.createJourney(r);N.advance(j,999999);assert.equal(j.pending.type,'waypoint');assert.equal(N.position(j).nodeId,r.waypointIds[0]);N.confirmStop(j);N.advance(j,999999);assert.equal(j.motion,'arrived');});
test('invalid edge offsets and transition edge positions rejected',()=>{assert.equal(N.validPosition({kind:'edge',edgeId:N.data.edges[0].id,offset:1.1}),false);assert.equal(N.validPosition({kind:'edge',edgeId:'e_entrance__e_lobby_1',offset:.5}),false);});
test('water stop at origin requires confirmation before moving',()=>{const r=N.planTrip({origin:{kind:'node',nodeId:'water_d'},destinationId:'D',viaWater:true}),j=N.createJourney(r);assert.equal(j.pending.type,'waypoint');N.advance(j,99);assert.deepEqual(N.position(j),r.origin);N.confirmStop(j);assert.equal(j.waypointsConfirmed.water_d,true);N.advance(j,10);assert.notDeepEqual(N.position(j),r.origin);});
console.log(`${checks} navigation groups passed; simulated data only.`);
